### ISSUE TITLE
Фиксь опросы.

### ISSUE THREAD

**Issue by FirstL1ght** [Spliterash/VkChat#3]
java.lang.NullPointerException
at ru.spliterash.vkchat.utils.VkUtils.getMessageAttachments(VkUtils.java:191)
at ru.spliterash.vkchat.utils.VkUtils.buildMessage(VkUtils.java:179)
at ru.spliterash.vkchat.vk.MessageTree.<init>(MessageTree.java:20)
at ru.spliterash.vkchat.VkChat.lambda$sendUserTextMessage$9$72a7ba46(VkChat.java:489)
at ru.spliterash.vkchat.VkChat.sendMessageToPlayers(VkChat.java:467)
at ru.spliterash.vkchat.VkChat.sendUserTextMessage(VkChat.java:487)
at ru.spliterash.vkchat.VkChat.processMessages(VkChat.java:345)
at ru.spliterash.vkchat.VkChat.processMessages(VkChat.java:296)
at ru.spliterash.vkchat.VkChat.access$000(VkChat.java:52)
at ru.spliterash.vkchat.VkChat$1.processMessages(VkChat.java:273)
at ru.spliterash.vkchat.vk.CallbackApiLongPoll.check(CallbackApiLongPoll.java:69)
at ru.spliterash.vkchat.VkChat.startLongPoll(VkChat.java:280)
at ru.spliterash.vkchat.VkChat.start(VkChat.java:216)
at ru.spliterash.vkchat.VkChat.lambda$onEnable$0(VkChat.java:108)
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
at com.destroystokyo.paper.ServerSchedulerReportingWrapp..(ServerSchedulerReportingWrapper.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Spliterash** [comment]
Laдnо.
